### ISSUE TITLE
Idea: About Page

### ISSUE THREAD

**Issue by mochet** [Joystream/gleev#10]
Currently Gleev has an unclear purpose to a new user, there is no statement on the site that clarifies what kind of content it is for.

Many sites include an about page for this purpose, so Gleev _really_ needs one.

Currently the best written definition of Gleev's intended purpose I have found is:
`Gleev has its sole focus on the Web3 and Crypto content vertical, bringing together the like-minded creators and viewers around the shared passion of the present and the future of Crypto affairs.`

This definition could be refined on the about page and made a bit easier to parse.

I have heard this issue being bought up by some users also, as it is quite a challenge for new users to understand what Gleev is, what its relationship with Joystream is etc.

**Comment by bedeho** [comment]
1. If you could make the problem more detailed, that would help. Who and when is someone trying to figure out exactly what about Gleev?
2. I have never read a single About page for any consumer app, so whatever the exact problem is, an About page is almostt certainly not an effective solution.

**Comment by mochet** [comment]
> 1. If you could make the problem more detailed, that would help. Who and when is someone trying to figure out exactly what about Gleev?
> 2. I have never read a single About page for any consumer app, so whatever the exact problem is, an About page is almostt certainly not an effective solution.

1. Assume we're talking about any new user who finds Gleev by coming across the video, if they visit the home page its not currently very clear what type of content Gleev is intended for. Unlike many video sites it having an intended genre of content is distinct and needs to be communicated to users somehow. This should inform users who are creators and or consumers.

2. About page may not be the best solution. One other thing may be to populate the left navigation bar similar to how Odysee does (https://odysee.com/)--if 3-4 crypto-relevant categories were highlighted here it would at least show a more specific area of content than it does currently.
Another possible improvement could be:
- a tagline, under the gleev logo that helps to better explain its purpose
- a banner on the front page that can at least be used in the short term so users know what type of content Gleev is about

The main reason I was suggesting an about page is that a user will be learning about Gleev + Joystream and it might make sense to have a page (whatever it is named) that explains "how it works".
