### ISSUE TITLE
Problem with "Top Movers" section on Gleev

### ISSUE THREAD

**Issue by leetjoy** [Joystream/gleev#61]
## Problem
Currently due to glitch "Top Movers", "Hot Tokens" sections does not very informative and displays tokens that are abandoned.
 
## Solution
I suggest removing or fixing it.

![image](https://github.com/user-attachments/assets/ddb9ab4f-6cd7-4ab5-ad8c-656bbac20cfa)

### How urgent this is?

It's blocking me right now

**Comment by leetjoy** [comment]
IMO., All creator tokens dashboard should be on top for easier discovery
![image](https://github.com/user-attachments/assets/9a7e67a1-60da-4c17-b7b5-40912ecc2165)

**Comment by leetjoy** [comment]
We got a CRT

appearing in `Hot Tokens`
<img width="1537" alt="Screenshot 2024-10-29 at 5 01 37 PM" src="https://github.com/user-attachments/assets/3d65f74b-5650-4a3b-99e1-21b2acbc3735">

`Top Movers`
<img width="1535" alt="Screenshot 2024-10-29 at 5 02 04 PM" src="https://github.com/user-attachments/assets/7b435cf6-2eba-4f03-ad94-d451a33779a8">

Top1 in `Price % 30D` - but the price did not even change in last 30 days
<img width="1548" alt="Screenshot 2024-10-29 at 5 02 59 PM" src="https://github.com/user-attachments/assets/34fa32b5-f3fd-4dc2-9ab9-46c652fe9b97">

I suggest fixing this

**Comment by Lezek123** [comment]
Fixed in Orion `4.1.0` (https://github.com/Joystream/orion/releases/tag/4.1.0) and Gleev `5.5.0` (https://github.com/Joystream/gleev/pull/67)
